name = "manifestation-app"
main = "src/index.js"
compatibility_date = "2024-03-14"

[[ d1_databases ]]
binding = "DB"
database_name = "manifestation_db"
database_id = "manifestation_db"
migrations_dir = "migrations"
